//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.21 at 02:41:19 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kennybastani.com/guides/customer-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kennybastani.guides.customer_service;
